# Generated by Django 3.2.5 on 2021-08-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aricle',
            new_name='article',
        ),
    ]
